== FusionAuth React SDK

An SDK for using FusionAuth in React applications.

=== Table of Contents

* link:#overview[Overview]
* link:#getting-started[Getting Started]
** link:#installation[Installation]
** link:#configuring-provider[Configuring Provider]
** link:#server-code-requirements[Server Code Requirements]
* link:#usage[Usage]
** link:#pre-built-buttons[Pre-built buttons]
** link:#programmatic-usage[Programmatic usage]
** link:#protecting-content[Protecting content]
** link:#known-issues[Known issues]
* link:#example-app[Example App]
* link:#documentation[Documentation]
* link:#releases[Releases]

=== Overview

This SDK supports authentication via the Authorization Code Grant. Once
authentication succeeds, the following secure, HTTP-only cookies will be
set:

* `access_token` - an OAuth
https://fusionauth.io/docs/v1/tech/oauth/tokens#access-token[Access
Token]
* `refresh_token` - a
https://fusionauth.io/docs/v1/tech/oauth/tokens#refresh-token[Refresh
Token] used to obtain a new `access_token`. This cookie will only be set
if refresh tokens are enabled on your FusionAuth instance.

Note that this setup requires you to have a server that performs the
OAuth token exchange. See link:#server-code-requirements[Server Code
Requirements] for more details.

You should be able to use this library against any version of FusionAuth
or any OIDC compliant identity server.

=== Getting Started

==== Installation

NPM:

[source,bash]
----
npm install fusionauth-react-sdk
----

Yarn:

[source,bash]
----
yarn add fusionauth-react-sdk
----

==== Configuring Provider

To configure the SDK, wrap your app with `FusionAuthProvider`:

[source,tsx]
----
import React from 'react';
import { createRoot } from 'react-dom/client';
import { FusionAuthProvider } from 'fusionauth-react-sdk';
import App from './App';

const container = document.getElementById('root');
const root = createRoot(container!);

root.render(
    <FusionAuthProvider
        baseUrl=""      // The base URL of your FusionAuth instance
        clientID=""     // Your FusionAuth client ID
        serverUrl=""    // The base URL of your server for the token exchange
        redirectUri=""  // The URI that the user is directed to after the login/register/logout action
    >
        <App />
    </FusionAuthProvider>
);
----

==== Server Code Requirements

Authenticating with FusionAuth requires you to set up a server that will
be used to perform the OAuth token exchange. This server must have the
following endpoints:

===== `POST /token-exchange`

This endpoint must:

. Call
https://fusionauth.io/docs/v1/tech/oauth/endpoints#complete-the-authorization-code-grant-request[/oauth2/token]
to complete the Authorization Code Grant request. The `code` and
`code_verifier` parameters should come from the request body, while the
rest of the parameters should be set/configured on the server side.
. Once the token exchange succeeds, read the `access_token` from the
response body and set it as a secure, HTTP-only cookie with the same
name.
. If you wish to support refresh tokens, repeat step 2 for the
`refresh_token` cookie.
. Call
https://fusionauth.io/docs/v1/tech/oauth/endpoints#userinfo[/oauth2/userinfo]
to retrieve the user info object and respond back to the client with
this object.

https://github.com/FusionAuth/fusionauth-example-react-sdk/blob/main/server/routes/token-exchange.js[Example
implementation]

===== `POST /jwt-refresh` (optional)

This endpoint is necessary if you wish to use refresh tokens. This
endpoint must:

. Call
https://fusionauth.io/docs/v1/tech/apis/jwt#refresh-a-jwt[/api/jwt/refresh]
to get a new `access_token` and `refresh_token`.
. Update the `access_token` and `refresh_token` cookies from the
response.

https://github.com/FusionAuth/fusionauth-example-react-sdk/blob/main/server/routes/jwt-refresh.js[Example
implementation]

=== Usage

==== Pre-built buttons

There are three pre-styled buttons that are configured to perform
login/logout/registration. They can be placed anywhere in your app as
is.

[source,tsx]
----
import {
    FusionAuthLoginButton,
    FusionAuthLogoutButton,
    FusionAuthRegisterButton
} from 'fusionauth-react-sdk';

export const LoginPage = () => (
    <>
        <h1>Welcome, please log in or register</h1>

        <FusionAuthLoginButton />

        <FusionAuthRegisterButton />
    </>
);

export const AccountPage = () => (
    <>
        <h1>Hello, user!</h1>

        <FusionAuthLogoutButton />
    </>
);
----

==== Programmatic usage

Alternatively, you may interact with the SDK programmatically using the
`useFusionAuth` hook or `withFusionAuth` HOC.

===== useFusionAuth

Use the `useFusionAuth` hook with your functional components to get
access to the properties exposed by
https://github.com/FusionAuth/fusionauth-react-sdk/blob/main/docs/context.md#fusionauthcontext[FusionAuthContext]:

[source,tsx]
----
import React from 'react';
import { useFusionAuth } from 'fusionauth-react-sdk';

const App = () => {
    const { login, logout, register, isAuthenticated } = useFusionAuth();

    return isAuthenticated ? (
        <div>
          <span>Hello, user!</span>
          <button onClick={() => logout()}>Logout</button>
        </div>
    ) : (
        <div>
          <button onClick={() => login()}>Log in</button>
          <button onClick={() => register()}>Register</button>
        </div>
    );
};
----

See
https://github.com/FusionAuth/fusionauth-react-sdk/blob/main/docs/functions.md#usefusionauth[useFusionAuth]
for more details.

===== withFusionAuth

The `withFusionAuth` higher-order component can be used to wrap your
components and give them access to a `fusionAuth` prop which contains
all the properties exposed by the `FusionAuthContext`. This works with
both functional and class components:

====== Functional Component

[source,tsx]
----
import React from 'react';
import { withFusionAuth, WithFusionAuthProps } from 'fusionauth-react-sdk';

const LogoutButton: React.FC<WithFusionAuthProps> = props => {
    const { logout } = props.fusionAuth;

    return <button onClick={() => logout()}>Logout</button>;
}

export default withFusionAuth(LogoutButton);
----

====== Class Component

[source,tsx]
----
import React, { Component } from 'react';
import { withFusionAuth, WithFusionAuthProps } from 'fusionauth-react-sdk';

class LogoutButton extends Component<WithFusionAuthProps> {
    render() {
        const { logout } = this.props.fusionAuth;
        return <button onClick={() => logout()}>Logout</button>;
    }
}

export default withFusionAuth(LogoutButton);
----

See
https://github.com/FusionAuth/fusionauth-react-sdk/blob/main/docs/functions.md#withfusionauth[withFusionAuth]
for more details.

===== State parameter

The `login` and `register` functions both accept an optional string
parameter called `state`. The state that is passed in to the function
call will be passed back to the `onRedirectSuccess` handler on your
`FusionAuthProvider`. Though you may pass any value you would like for
the state parameter, it is often used to indicate which page the user
was on before redirecting to login or registration, so that the user can
be returned to that location after a successful authentication.

==== Protecting Content

The `RequireAuth` component can be used to protect information from
unauthorized users. It takes an optional prop `withRole` that can be
used to ensure the user has a specific role.

[source,tsx]
----
import { RequireAuth, useFusionAuth } from 'fusionauth-react-sdk';

const UserNameDisplay = () => {
    const { user } = useFusionAuth();

    return (
        <RequireAuth>
            <p>User: {user.name}</p> // Only displays if user is authenticated
        </RequireAuth>
    );
};

const AdminPanel = () => (
    <RequireAuth withRole="admin">
        <button>Delete User</button> // Only displays if user is authenticated and has 'admin' role
    </RequireAuth>
);
----

==== Known Issues

===== Token exchange endpoint being called repeatedly

If you see the token exchange endpoint being called multiple times, this
is due to a dev time setting in React 18. When running using
`StrictMode` in development mode, React 18 will mount, unmount, and
remount all components in this mode, which results in the network call
running twice.

This will not happen in a production build or if `StrictMode` is
disabled.

If you remove the `React.StrictMode` tags in `index.tsx` of the example
app, the call is only made once.

=== Example App

See the
https://github.com/FusionAuth/fusionauth-example-react-sdk[FusionAuth
React SDK Example] for functional example of a React client that
utilizes the SDK as well as an Express server that performs the token
exchange.

=== Documentation

https://github.com/FusionAuth/fusionauth-react-sdk/blob/main/docs/documentation.md[Full
library documentation]

=== Releases

To perform a release:

* Pull the code to your local machine
* Bump the version in `package.json`
* Run `npm webpack`
* Run `npm publish`

You may have to set up your machine to be able to publish, which will
involve updating your .npmrc file.

There's information
https://dev.to/alexeagleson/how-to-create-and-publish-a-react-component-library-2oe[here
that you can use] to do that (look for the `.npmrc` section).
